MAPEO_ATRIBUTOS_ES = {
    #Tela
    "cotton" : "algodón",
    "polyester" : "poliéster",
    "cotton/polyester blend" : "algodón/poliéster",

    # Estilos
    "sports style": "deportiva",
    "casual style": "casual",
    "urban style": "urbana",
    "retro style": "retro",

    # Colores
    "black": "negro",
    "white": "blanco",
    "red": "rojo",
    "blue": "azul",
    "green": "verde",
    "yellow": "amarillo",
    "gray": "gris",
    "orange": "naranja",
    "purple": "morado",
    "sky blue": "celeste",

    # Cuello
    "round neck": "cuello redondo",
    "V-neck": "cuello en V",
    "polo collar": "cuello polo",

    # Mangas
    "short sleeves": "manga corta",
    "long sleeves": "manga larga",

    # Diseños
    "striped": "rayas",
    "lined": "líneas",
    "geometric": "geométrico",
    "abstract": "abstracto",
    "paint splatter": "manchas de pintura",
    "gradient": "degradado",
    "other": "otro",

    # Estilos avanzados
    "brush strokes": "brochazos",
    "splatter": "salpicaduras",
    "minimalist": "minimalista",
    "futuristic": "futurista",
    "camouflage": "camuflaje",

    #Ajuste
    "slim fit": "ajuste estrecho",
    "regular fit": "ajuste regular",
    "loose fit": "ajuste relajado",

    #Cintura
    "elastic waistband": "cintura elástica",
    "drawstring waistband": "cintura con cordón",
    "adjustable waistband": "cintura ajustable",
    "standard waistband": "cintura estándar",

    #Bolsillos
    "side pockets": "bolsillos laterales",
    "back pockets": "bolsillos traseros",
    "cargo pockets": "bolsillos de carga",
    "no pockets": "sin bolsillos",

    # Acabados
    "matte finish": "mate",
    "glossy finish": "brillante",
    "textured finish": "texturizado",

    # Género
    "male": "hombre",
    "female": "mujer",
    "unisex": "unisex",

    #Chompa
    "hooded": "con capucha",
    "zipper closure": "con cierre",
    "no closure": "sin cierre",
    "kangaroo pocket": "bolsillo canguro",

    #Conjunto Interno
    "two-piece": "dos piezas",
    "sportswear set": "conjunto deportivo",   
    "sleeveless shirt": "camiseta sin mangas",
    "short sleeve shirt": "camiseta manga corta",
    "lightweight long sleeve shirt": "camiseta manga larga ligera",
    "short shorts": "short corto",
    "three-quarter shorts": "short 3/4",
    "compression tights": "malla interna/licra",

    #Conjunto Externo
    "with hood": "con capucha",
    "without hood": "sin capucha",
    "with zipper": "con cierre",
    "no zipper": "sin cierre",
    "slim fit": "ajuste estrecho",
    "regular fit": "ajuste regular",
    "loose fit": "ajuste suelto",
    "elastic waistband": "cintura elástica",
    "drawstring waistband": "cintura con cordón",
    "side pockets": "bolsillos laterales",
    "back pockets": "bolsillos traseros",
    "no pockets": "sin bolsillos",
}


# --------------------------------------
# Diccionario básico EN → ES (para mostrar al cliente)
# --------------------------------------
TRADUCCION_BASICA_INVERSA = {
    # prendas
    "T-shirt": "camiseta",
    "sports T-shirt": "camiseta deportiva",
    "jogger pants": "pantalón jogger",
    "pants": "pantalón",
    "shorts": "pantaloneta",
    "hoodie": "chompa",
    "hoodie jacket": "chompa con cierre",
    "jacket": "chaqueta",
    "outfit": "conjunto",
    "set": "conjunto",
    "two-piece": "dos piezas",
    "sportswear set": "conjunto deportivo",

    # estilos
    "sports style": "deportiva",
    "urban style": "urbana",
    "casual style": "casual",
    "retro style": "retro",

    # detalles generales
    "round neck": "cuello redondo",
    "V-neck": "cuello en V",
    "polo collar": "cuello polo",
    "short sleeves": "manga corta",
    "long sleeves": "manga larga",
    "sleeveless": "sin mangas",
    "gradient": "degradado",
    "paint splatter": "manchas de pintura",
    "geometric": "geométrico",
    "abstract": "abstracto",
    "ribbed details on collar and sleeves": "ribetes en cuello y mangas",
    "bicolor sleeves and collar": "bicolor en mangas/cuello",
    "visible seams": "costuras visibles",

    # acabado/estudio
    "matte finish": "acabado mate",
    "glossy finish": "acabado brillante",
    "textured finish": "acabado texturizado",
    "professional studio lighting": "iluminación profesional de estudio",
    "studio lighting": "iluminación de estudio",
    "product catalog photo": "foto de catálogo de producto",
    "plain white background": "fondo blanco liso",
    "isolated background": "fondo aislado",
    "sharp focus": "enfoque nítido",
    "no wrinkles": "sin arrugas",
}

TRADUCCIONES = {
    "round neck": "cuello redondo",
    "V-neck": "cuello en V",
    "polo collar": "cuello polo",
    "short sleeves": "manga corta",
    "long sleeves": "manga larga",
    "cotton": "algodón",
    "polyester": "poliéster",
    "cotton/polyester blend": "mezcla algodón/poliéster",
    "male": "hombre",
    "female": "mujer",
    "unisex": "unisex",
    "linear": "lineal",
    "radial": "radial",
    "vertical": "vertical",
    "horizontal": "horizontal",
    "diagonal": "diagonal",
    "soft": "suave",
    "medium": "media",
    "hard": "fuerte",
    "gradient": "degradado",
    "heather": "moteado",
    "geometric": "geométrico",
    "abstract": "abstracto",
    "ribbed details on collar and sleeves": "ribetes en cuello y mangas",
    "bicolor sleeves and collar": "bicolor en mangas/cuello",
    "visible seams": "costuras visibles",
    "solid": "liso",
    "stripes": "rayas",
    "camouflage": "camuflaje",
    "two_tone": "dos tonos",
    "full_print": "diseño completo",
    "density": "densidad",
    "contrast": "contraste",
    "grain": "grano/trama",
    "light": "ligera",
    "medium": "media",
    "heavy": "alta",
    "low": "bajo",
    "high": "alto",
    "fine": "fino",
    "regular": "regular",
    "coarse": "grueso",
    "shape": "figura",
    "triangles": "triángulos",
    "squares": "cuadrados",
    "hexagons": "hexágonos",
    "chevrons": "chevrons",
    "small": "pequeña",
    "large": "grande",
    "tight": "ajustado",
    "loose": "amplio",
    "centered": "centrado",
    "offset": "desfasado",
    "flat, non-overlapping": "sin superposición",
    "slightly overlapping, layered": "ligeramente superpuesto",
    "shattered, fragmented, dynamic": "fragmentado y roto",
    "scale": "escala",
    "spacing": "espaciado",
    "alignment": "alineación",
    "layering": "superposición",
    "small": "pequeña",
    "large": "grande",
    "tight": "ajustado",
    "loose": "amplio",
    "centered": "centrado",
    "offset": "desfasado",
    "flat, non-overlapping": "sin superposición",
    "slightly overlapping, layered": "ligeramente superpuesto",
    "shattered, fragmented, dynamic": "fragmentado y roto",
    "style": "estilo",
    "intensity": "intensidad",
    "coverage": "cobertura",
    "flow_direction": "dirección/flujo",
    "brush strokes": "pinceladas",
    "paint splatter": "salpicaduras",
    "fluid": "fluido",
    "smoke": "humo",
    "organic": "orgánico",
    "subtle": "sutil",
    "balanced": "equilibrado",
    "bold": "marcado",
    "all-over full coverage": "completa",
    "partial central area": "parcial",
    "subtly dispersed elements": "distribución sutil",
    "random": "aleatorio",
    "flowing vertically": "vertical",
    "sweeping diagonally": "diagonal",
    "direction": "dirección",
    "horizontal": "horizontal",
    "vertical": "vertical",
    "diagonal": "diagonal",
    "thickness": "grosor de raya",
    "thin": "delgada",
    "medium": "media",
    "thick": "gruesa",
    "tight": "ajustado",
    "regular": "regular",
    "wide": "amplio",
    "hard edge": "definido",
    "soft edge": "difuminado",
    "uniform and continuous": "uniforme y continuo",
    "thick block segments": "bloques gruesos",
    "staggered and offset": "desfasado y desplazado",
    "varied thickness": "grosor variado",
    "palette": "paleta",
    "earth tones": "tonos tierra",
    "forest": "bosque",
    "desert": "desierto",
    "urban gray": "urbano gris",
    "vibrant": "vibrante",
    "scale": "escala",
    "small": "pequeña",
    "medium": "media",
    "large": "grande",
    "edge": "borde",
    "organic shapes": "formas orgánicas",
    "soft edged": "difuminado",
    "micro-pixelated": "micro-pixelado",
    "splintered fragmented shapes": "fragmentado moderno",
    "layered and outlined": "superpuesto (moderno)",
    "division": "división",
    "horizontal": "horizontal",
    "vertical": "vertical",
    "diagonal": "diagonal",
    "division_style": "estilo de borde",
    "straight line": "recto",
    "curved line": "curvo",
    "V-shaped": "en V",
    "wavy line": "ondulado",
    "ratio": "relación de áreas",
    "clean edge": "limpio",
    "soft transition": "difuminado",
    "full color block": "bloque completo",
    "offset panel": "panel desfasado",
    "asymmetrical panel": "panel asimétrico",
    "sleeve and body split": "mangas y cuerpo",
    "complexity": "complejidad",
    "simple": "simple",
    "moderate": "media",
    "complex": "alta",
    "density": "densidad",
    "dense": "densa",
    "seamless repetition": "repetición sin costuras",
    "scatterred elements": "elementos dispersos",
    "sparse minimalist": "minimalista",
    "random": "aleatorio",
    "texture": "textura",
    "digital glitch art": "digital glitch art",
    "watercolor texture": "textura de agua",
    "vector art": "arte vectorial",
    "motif": "objeto/forma",
    "style": "arte/estilo",
    "manga": "manga",
    "pinceladas": "pinceladas",
    "animado": "animado",
    "motif": "objeto/forma",
    "style": "arte/estilo",
    "manga": "manga",
    "pinceladas": "pinceladas",
    "animado": "animado",
    "motif": "objeto/forma",
    "style": "arte/estilo",
    "manga": "manga",
    "pinceladas": "pinceladas",
    "animado": "animado",
    "black": "Negro",
    "white": "Blanco",
    "red": "Rojo",
    "blue": "Azul",
    "green": "Verde",
    "yellow": "Amarillo",
    "gray": "Gris",
    "orange": "Naranja",
    "purple": "Morado",
    "sky blue": "Celeste",
    "round neck": "Redondo",
    "V-neck": "En V",
    "polo collar": "Polo",
    "short sleeves": "Corta",
    "long sleeves": "Larga",
    "cotton": "Algodón",
    "polyester": "Poliéster",
    "cotton/polyester blend": "Mezcla Algodón/Poliéster",
    "male": "Hombre",
    "female": "Mujer",
    "unisex": "Unisex",
    "short sleeves": "Corta",
    "long sleeves": "Larga",
    "cotton": "Algodón",
    "polyester": "Poliéster",
    "cotton/polyester blend": "Mezcla Algodón/Poliéster",
    "male": "Hombre",
    "female": "Mujer",
    "unisex": "Unisex",
    "sportswear": "deportiva"

 
}



